### ISSUE TITLE
Delete monitor not working as expected

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#10]
Expected output:
Monitor will be deleted at database.

Actual Output:
Delete monitor with Id 7.
![image](https://user-images.githubusercontent.com/28770143/81703337-07375880-949f-11ea-8b91-6a8e9453b9ed.png)

Still existing in monitor table
![image](https://user-images.githubusercontent.com/28770143/81703436-29c97180-949f-11ea-8ea1-888c2aa5f9b7.png)

Replicate:

1. Delete any monitor with existing id.
2. Check database for confirmation

**Comment by zheuswalker** [comment]
column rmd_isRemoved is the identifier to check if the monitor is deleted or not. There is no permanent delete.

**Comment by jaymendez** [comment]
When deleting monitor, it should also delete the monitor-patient join table data.

Example,
Deleting monitor with id 1 would also delete the join table data where monitor_id = 1

![image](https://user-images.githubusercontent.com/28770143/81951999-78f6da00-9638-11ea-9d4f-2eeecea0a495.png)

Highlighted data should also be deleted.

**Comment by zheuswalker** [comment]
updated on commit https://github.com/zheuswalker/up-pgh/commit/2a898c3013f1949e9a5990d3a64e836e39719437
