### ISSUE TITLE
Feature Request: Get monitor with Id

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#12]
![image](https://user-images.githubusercontent.com/28770143/82004444-81313280-9695-11ea-8a87-92a1dfaab600.png)

**Comment by zheuswalker** [comment]
inserted at commit https://github.com/zheuswalker/up-pgh/commit/cd4915d891ba8d8dffbd29f4d616a37ac21db641 .

**Comment by jaymendez** [comment]
Not working, when fetching monitor with id 19, it returns a different result

![image](https://user-images.githubusercontent.com/28770143/82230598-84127880-995e-11ea-975f-2fa5afe01206.png)

Even when changing 19 to a different id, monitor id 20 is still the result

**Comment by zheuswalker** [comment]
Try it again, it was a mistake, the procedure uses a static variable id.

**Comment by jaymendez** [comment]
![image](https://user-images.githubusercontent.com/28770143/82397143-50307380-9a82-11ea-9db7-f2df0c225742.png)


![image](https://user-images.githubusercontent.com/28770143/82397179-65a59d80-9a82-11ea-9a71-9abdcce0598b.png)
