### ISSUE TITLE
Feature request: Remove slotnumber on add_patient_toMonitor API

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#14]
![image](https://user-images.githubusercontent.com/28770143/82011974-1f7ac380-96a9-11ea-8ed6-47e681ab161b.png)

**Comment by zheuswalker** [comment]
Updated on commit https://github.com/zheuswalker/up-pgh/commit/2a898c3013f1949e9a5990d3a64e836e39719437
