### ISSUE TITLE
Remove patient from Monitor not working.

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#15]
Steps to replicate:
1. Add Patient-id 8 to Monitor 20
2. Get Monitor to confirm add.
3. Remove Patient to Monitor
4. Get Monitor

Expected:
Patient-id 8 should be removed to monitor 20

Actual:
Patient-id 8 did not get removed at monitor 20

![can't remove patient to monitor](https://user-images.githubusercontent.com/28770143/82114359-f896bd00-978e-11ea-9c43-1f63960afcb6.png)

![image](https://user-images.githubusercontent.com/28770143/82114338-d604a400-978e-11ea-802f-1fcd1176ffcb.png)

**Comment by zheuswalker** [comment]
Updated on commit https://github.com/zheuswalker/up-pgh/commit/2a898c3013f1949e9a5990d3a64e836e39719437 .

**Comment by jaymendez** [comment]
Still not working

**Comment by zheuswalker** [comment]
Try it again. The procedure parameters were disarranged.

**Comment by jaymendez** [comment]
When removing patient from monitor, it removes all patient instead of the given patient Id.

**Comment by zheuswalker** [comment]
Try it again  forgot to add the patientid on the where clause.
