### ISSUE TITLE
Feature Request: New fields for Create Patient and Update Patient and List Patient API

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#16]
Add new fields for Patient API.
![image](https://user-images.githubusercontent.com/28770143/82123289-24d02f00-97cb-11ea-806f-6bed76e774a5.png)

**Comment by zheuswalker** [comment]
inserted on commit https://github.com/zheuswalker/up-pgh/commit/48340926845def98558417dec9c4807c20ba271f .
