### ISSUE TITLE
Create Patient API 

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#19]
When creating patient, instead of the user specified **bed number**, 

![image](https://user-images.githubusercontent.com/28770143/82734763-9f5ef880-9d4f-11ea-9116-f7c3791731ad.png)

it has a static value of 2.
![image](https://user-images.githubusercontent.com/28770143/82734779-b6054f80-9d4f-11ea-8f83-1bd6f090f54d.png)

**Comment by zheuswalker** [comment]
![image](https://user-images.githubusercontent.com/33520349/82743837-4caf2c00-9da3-11ea-9610-f3ff84b41dba.png)
What api are you using. I received not a static value for bednumber.

**Comment by zheuswalker** [comment]
If you're using api [ http://206.189.87.169/getpatientlist ] , then check the front end code, since im returning the correct bed number. 
![image](https://user-images.githubusercontent.com/33520349/82743861-b3344a00-9da3-11ea-9ddc-b23bb37d37f0.png)
