### ISSUE TITLE
SQL Error when using Get Ward API

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#2]
When using this API 

`{baseUrl}/get_ward`

I receive an SQL error, 

![image](https://user-images.githubusercontent.com/28770143/81478387-a36b2080-924f-11ea-8909-312c960649bd.png)

**Comment by zheuswalker** [comment]
Fix. 

https://apitester.com/shared/checks/ab3812a7557f40098c25fb86df8349af
