### ISSUE TITLE
Feature request: make pusher docker a service

### ISSUE THREAD

**Issue by mrnivlac** [zheuswalker/up-pgh#21]
1. Copy the following code to `/etc/systemd/system/local-pusher.service`
2. `systemctl daemon-reload`
3. `systemctl enable local-pusher`
4. `systemctl start local-pusher`
5. Check the status using `systemctl status local-pusher`
6. Check logs using `journalctl -f -u local-pusher`. `-f` argument means to tail the logs

```
[Unit]
Description=pusher docker

[Service]
ExecStart=docker-compose -f /var/www/html/pusher_docker/docker-compose.yml up
Type=simple
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by zheuswalker** [comment]
fixed on commit https://github.com/zheuswalker/up-pgh/commit/4fa2aa6f97cb52bb58675f3bd70eaa2791459e4c .
