### ISSUE TITLE
AddPatientConfig API

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#30]
fields shouldn't be required, or fields should be nullable. 
![image](https://user-images.githubusercontent.com/28770143/88451505-c047e500-ce89-11ea-8db9-640985e8bd4f.png)

**Comment by zheuswalker** [comment]
Fixed in commit https://github.com/zheuswalker/up-pgh/commit/d2b911d80d6b1bdd1fcbda2a20dfe84f0a726318
