### ISSUE TITLE
Create Patient Config inserting wrong value and wrong column

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#33]
Creation of patient config of patient_id 55

![image](https://user-images.githubusercontent.com/28770143/90895713-25451b00-e3f5-11ea-961e-3e896f0eb5c8.png)

Get patient config of patient_id 55
![image](https://user-images.githubusercontent.com/28770143/90895779-3a21ae80-e3f5-11ea-9d44-758fb5825afd.png)

**Comment by zheuswalker** [comment]
pacheck nalang

**Comment by zheuswalker** [comment]
Pacheck nalang ulit, nasa stored procedures kase yung mali.
