### ISSUE TITLE
invalid birthdate format when requesting to read patient details

### ISSUE THREAD

**Issue by mrnivlac** [zheuswalker/up-pgh#4]
to replicate the issue:
1. make an HTTP call: `GET /Patient/{patient-id}` for any `patient-id` (e.g. `/Patient/8`)
2. in the response body, `birthDate` has the format 'MM/DD/YYYY`

the correct `birthDate` format is 'YYYY-MM-DD`
* YYYY is the complete year (e.g. 2020)
* MM is from 01 (Jan) to 12 (Dec)
* DD is from 01 to 31

suggestion to fix the issue:
1. store birthdate as a date type
2. format the birthdate when responding to the request

this issue affects:
* API for create, read, and update of patient in the frontend

**Comment by zheuswalker** [comment]
![image](https://user-images.githubusercontent.com/33520349/81603761-7494ac00-9401-11ea-80ec-e4c5b9b3a853.png)

**Comment by mrnivlac** [comment]
the birthdate should be YYYY-MM-DD. MM is `01` to `12` instead of the full month name like `April`

**Comment by zheuswalker** [comment]
![Uploading image.png…]()

**Comment by zheuswalker** [comment]
![image](https://user-images.githubusercontent.com/33520349/81705604-cd1b8600-94a1-11ea-903b-1a70a59b3774.png)

**Comment by mrnivlac** [comment]
fixed
