### ISSUE TITLE
500 when requesting to create simple observation due to duplicate id

### ISSUE THREAD

**Issue by mrnivlac** [zheuswalker/up-pgh#6]
note: fix #5 first before this one so that we use the correct request body format.

to replicate the issue:
1. make an HTTP call `/POST /Observation` with request body below
2. response code is 500 with excerpt from response body: `Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2147483647' for key 'tpo_id'`
```json
{
    "resourceType": "Observation",
    "id": "1123123",
    "status": "final",
    "code": {
        "coding": [
            {
                "code": "59407-7",
                "system": "http://loinc.org"
            }
        ]
    },
    "subject": {
        "reference": "Patient/1"
    },
    "effectiveDateTime": "2014-12-05T09:30:10+08:00",
    "valueQuantity": {
        "value": 98,
        "system": "http://unitsofmeasure.org",
        "code": "%",
        "unit": "%"
    }
}
```

proposed solution:
1. ignore the id
2. auto-generate id when storing the observation on the db

**Comment by zheuswalker** [comment]
close on commit
