### ISSUE TITLE
observation effective datetime is stored as string

### ISSUE THREAD

**Issue by mrnivlac** [zheuswalker/up-pgh#7]
to replicate the issue:
1. make an HTTP call `POST /Observation` with request body below
2. check the stored observation using `SELECT * FROM ``t_patient_observation``  WHERE ``tpo_subject`` = 'Patient/1' ORDER BY ``t_patient_observation``.``tpo_effectivity``  DESC`
3. the returned `tpo_effectivity` is a string
```json
{
    "resourceType": "Observation",
    "id": "1123123",
    "status": "final",
    "code": {
        "coding": [
            {
                "code": "59407-7",
                "system": "http://loinc.org"
            }
        ]
    },
    "subject": {
        "reference": "Patient/1"
    },
    "effectiveDateTime": "2014-12-05T09:30:10+08:00",
    "valueQuantity": {
        "value": 98,
        "system": "http://unitsofmeasure.org",
        "code": "%",
        "unit": "%"
    }
}
```

proposed solution:
1. `effectiveDateTime` should be parsed. it has the format `YYYY-MM-DDThh:mm:ss+zz:zz`
2. store it as datetime type in SQL

this issue affects:
* the API for when the frontend receives the effectiveDateTime for new observations
* sorting for the latest observation

**Comment by zheuswalker** [comment]
Fixed.

http://206.189.87.169/getPatientObservation


Check also procedure ->  sp_getPatientObservations()

: Order by latest obs_id (auto_increment) group by subject (patient)

**Comment by mrnivlac** [comment]
Observations should be ordered by effectiveDateTime, not obs_id; because, the most recently inserted observation is not guaranteed to have the latest effectiveDateTime.

Example:
* observation 34 is inserted with effectiveDateTime 2014-12-05T09:30:10+08:00
* observation 35 is inserted with effectiveDateTime 2014-12-05T09:30:00+08:00
the current query will return observation 35, which is older than 34.

**Comment by zheuswalker** [comment]
ok ok

**Comment by zheuswalker** [comment]
Check the procedure and the table again, i changed it now to datetime.
