### ISSUE TITLE
t_patient_observation table does not include fields for system, code, and unit

### ISSUE THREAD

**Issue by mrnivlac** [zheuswalker/up-pgh#8]
to replicate the issue:
1. run `SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = `'t_patient_observation'``

the table should include:
|column|type|example|
|---|---|---|
|system|VARCHAR(255)|`http://unitsofmeasure.org`|
|code|VARCHAR(50)|`{Beats}/min`|
|unit|VARCHAR(50)|`Beats / minute`|

These fields indicate the units that were used to express the observation value. These fields should not be associated with the observation code

**Comment by zheuswalker** [comment]
fixed on commit  https://github.com/zheuswalker/up-pgh/commit/dc3eb8bac6ba31a24b0c5ebcf1d7ef8c8799c76f
