### ISSUE TITLE
Wrong results for Get Monitor API

### ISSUE THREAD

**Issue by jaymendez** [zheuswalker/up-pgh#9]
Expected Output:
![image](https://user-images.githubusercontent.com/28770143/81518676-639c5a00-9371-11ea-87d2-458d74afdab6.png)

Actual Output:
![image](https://user-images.githubusercontent.com/28770143/81518656-541d1100-9371-11ea-9f81-25e9d97e1b4e.png)

**Comment by zheuswalker** [comment]
i return patientid as string, just convert it into array, extract the value from array or explode it.

![image](https://user-images.githubusercontent.com/33520349/81611011-f211e980-940c-11ea-9108-05d026d46a5e.png)

**Comment by zheuswalker** [comment]
fix on commit https://github.com/zheuswalker/up-pgh/commit/fb34bf9f1578394141d7ac1c1a6f4d465d9792e2
